import { NextRequest, NextResponse } from "next/server";
import { buildChatQuestion, buildConciseAssistantReply } from "@/lib/appApi";
import { openRouterChat, AGENT_MODEL } from "@/lib/openrouter";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const sectionIndex = Math.max(0, Number(body?.section_index ?? 0));
    const messages = Array.isArray(body?.messages) ? body.messages : [];

    const question = buildChatQuestion(sectionIndex);

    // Build messages for the model: preserve prior chat, add RFP context and instruction
    const modelMessages: any[] = [];
    modelMessages.push({
      role: "system",
      content:
        "You are a ChatGPT-style proposal-writing assistant with a warm, slightly chatty voice. Be helpful and a little yappy in a good way: explain what the current section means, why it matters, and what you still need. Ask the defined section question for the current step, and if the answer is incomplete, clearly say what is missing and invite the user to share what they do know or let you infer it from the RFP context. Do NOT output JSON or metadata - return only the assistant reply text.",
    });

    if (body?.rfp_context) {
      modelMessages.push({ role: "system", content: `RFP CONTEXT:\n${body.rfp_context}` });
    }

    // Include prior messages (if any)
    for (const m of messages) {
      if (!m || !m.role) continue;
      // Add user messages to model messages
      modelMessages.push({ role: m.role, content: String(m.content || "") });
    }

    // Instruction for the current step
    modelMessages.push({
      role: "user",
      content: `Please respond in a friendly, slightly chatty way for section #${sectionIndex}. ${question} If the user answer is incomplete, explicitly call out the missing detail, explain it in plain language, and ask for it. If the user just acknowledged, give a helpful nudge with a little context so the flow still feels conversational.`,
    });

    // Use a faster intake model when available and limit tokens for speed.
    const fastModel = AGENT_MODEL.TEMPLATE_FORMATTING;

    // If the user's last message looks like a greeting, ask the model to reply conversationally
    const lastUser = Array.isArray(messages) ? [...messages].reverse().find((m: any) => m.role === "user") : null;
    const lastText = lastUser ? String(lastUser.content || "").trim() : "";
    const isGreeting = !!lastText.match(/^\s*(hi|hello|hey|yo|howdy|good\s+(morning|afternoon|evening))\b/i);

    if (isGreeting) {
      modelMessages.unshift({
        role: "system",
        content: "If the user message appears to be a greeting or short chit-chat, reply conversationally and do not advance the section index. Ask if they are ready to continue or if they'd like to ask a question about the RFP. Keep a friendly, chatty tone.",
      });
    }

    // Use the model directly and wait a bit longer so replies are generated by the LLM (avoid very-short timeouts).
    let reply: string | null = null;
    try {
      const modelResp = await openRouterChat({
        model: fastModel,
        messages: modelMessages,
        temperature: 0.2,
        max_tokens: 512,
      });
      reply = modelResp;
    } catch (err) {
      console.error("[proposal-chat] OpenRouter error:", err);
    }

    // Fast fallback when OpenRouter is slow or fails
    if (!reply) {
      // Fallback: be a little more helpful even when model is unavailable
      reply = `${buildConciseAssistantReply(sectionIndex)} I can help fill in missing parts — tell me what you already have and I’ll help.`;
    }

    if (sectionIndex < 14 && !reply.includes("?")) {
      reply = `${reply}\n\n${question} If that information is missing, say what you know and I’ll infer the rest from the RFP context.`;
    }

    return NextResponse.json({
      reply,
      proposal_ready: sectionIndex >= 13,
      section_index: Math.min(sectionIndex + 1, 14),
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
